FROM node:16-alpine

RUN apk update
RUN apk upgrade --available

RUN mkdir /client
COPY . /client

ENV PATH=/node_modules/.bin:$PATH
COPY package*.json ./

RUN npm install

WORKDIR /client
ENV NODE_ENV DEV
EXPOSE 3000

ENTRYPOINT ["npm", "run", "start"]
