FROM node:16-alpine

RUN apk update
RUN apk upgrade --available

RUN mkdir /client
COPY . /client

WORKDIR /client
RUN npm install

ENV REACT_APP_NODE_ENV DEV
EXPOSE 3000

ENTRYPOINT ["npm", "run", "start"]
