version: '3.8'

services:

  api:
    container_name: spotify.api
    build: ./api
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/app:/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    env_file:
      - .env
    depends_on:
      - mongo_db

  mongo_db:
    container_name: spotify.mongo_db
    image: mongo
    env_file:
      - .env