version: '3.8'

services:

  api:
    container_name: spotify.api
    build: ./api
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/app:/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - MONGO_USER=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_AUTH_SOURCE=${MONGO_AUTH_SOURCE}
      - MONGO_HOST=mongo_db
    env_file:
      - .env
    depends_on:
      - mongo_db

  mongo_db:
    container_name: spotify.mongo_db
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./mongo-volume:${MONGODB_DATA_DIR}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGODB_DATA_DIR=${MONGODB_DATA_DIR}
    env_file:
      - .env

  client:
    container_name: spotify.client
    command: bash -c "rm -rf /client/node_modules/*"
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - exclude:/client/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  exclude:
